<?php

use Illuminate\Database\Seeder;

class AreasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('areas')->insert(['nombre' => 'Aprendizaje de máquina', 'descripcion' => 'Es una rama de inteligencia artificial cuyo objetivo es desarrollar algoritmos que permitan a los computadores aprender automáticamente e ir mejorando tal aprendizaje con la experiencia. Entiéndase por aprender a, reconocer patrones complejos y tomar decisiones inteligentes basadas en dichos patrones.  De esta forma, los computadores serán capaces de generalizar comportamientos a partir de cierta información suministrada en forma de ejemplos. Cabe destacar que esta es una área multidisciplinaria, que tuvo-tiene-tendrá un gran impacto en múltiples aplicaciones como: procesamiento de lenguaje, previsión del clima, reconocimiento de patrones, juegos, minería de datos, sistemas expertos, robótica, entre otras.']);

        DB::table('areas')->insert(['nombre' => 'Lógica fuzzy, minería de datos y descubrimiento de conocimiento en big data', 'descripcion' => 'La teoría de conjuntos fuzzy y la lógica fuzzy son una extensión de la teoría de conjuntos clásica y la lógica clásica, enfocada a tratar problemas con información vaga, imprecisa e incompleta. Los sistemas fuzzy proveen un mecanismo automático para representar y procesar este tipo de información que se encuentra en casi todos los problemas del mundo real. La minería de datos es el proceso computacional utilizado para descubrir patrones o conocimiento de un conjunto de datos, que sea entendible por el usuario, mediante la utilización de métodos basados en inteligencia artificial, aprendizaje de máquina, estadísticas y bases de datos. Cuando ese conjunto de datos supera la capacidad del software actual para ser procesados y se halla en constante crecimiento, nos encontramos frente a una base de datos denomida Big Data.']);

        DB::table('areas')->insert(['nombre' => 'Procesamiento de imágenes y visión computacional', 'descripcion' => 'Visión por computador (o interpretación de imágenes) representa un sub-area de la Inteligencia Artificial que tiene como objetivo el análisis y la interpretación de la información visual. La comprensión de la imagen se considera como un proceso que parte en una imagen o secuencia de imágenes (por ejemplo, proyecciones 2D de una escena estática o dinámica) y termina en una descripción interna de la escena. Los problemas de la interpretación de imágenes son el núcleo de los esfuerzos actuales para permitir hacer una máquina que tenga interacciones "inteligentes" con su entorno. Los sensores se utilizan para obtener información de su entorno 3D que puede ocurrir en forma de lenguaje natural, imágenes, sonidos, etc.. Esta información se procesa con el fin de llegar a las diferentes formas de representación interna, permitiendo que la máquina interactúe con el medio ambiente, ya sea en forma lingüística o por alguna acción del robot. Las representaciones internas forman el "conocimiento" o los "modelos" de la visión por computador basada en el conocimiento. De acuerdo a la metodología convencional, la complejidad de los pasos del proceso se domina mediante la formulación y el estudio de cada problema cognitivo en tres niveles independientes entre sí, los niveles de la teoría computacional, algoritmos e implementación(Marr D. 1982. Vision).']);

        DB::table('areas')->insert(['nombre' => 'Representación del conocimiento', 'descripcion' => 'En sus inicios, la investigación en Inteligencia Artificial (IA) se centró en el desarrollo de formalismos, mecanismos de inferencia y herramientas para poner en práctica Sistemas Basados en Conocimiento (SBC). Típicamente, los esfuerzos de desarrollo se limitaron a la realización de SBC pequeños, a fin de estudiar la viabilidad de nuevos enfoques. Aunque estos estudios dieron a luz resultados prometedores, la transferencia de esta tecnología para la construcción de SBC comerciales fracasó en muchos casos. Esta situación fue comparable con la “crisis del software” de la años 60. Así como la crisis del software trajo como resultado el establecimiento de la disciplina de Ingeniería de Software (IS), la situación insatisfactoria en la construcción de SBC puso de manifiesto la necesidad de enfoques más metodológicos. De esta manera, el objetivo de la Ingeniería del Conocimiento (IC) es similar al de la IS: tornar la construcción de SBC en un proceso sistemático y controlable. Esto requiere análisis de los procesos de construcción y mantenimiento así como el desarrollo de métodos, lenguajes y herramientas adecuadas. La nueva Ingeniería del Conocimiento surge para disminuir esta brecha y para hacer del Ingeniero del Conocimiento, el principal actor e interface entre la tecnología y la gestión. Para esto, reconoce la importancia del proceso de modelado y de la visión sistémica del ingeniero. Pero esta no es una tarea fácil ya que generalmente la Gestión del Conocimiento desconoce la existencia de la IC, atribuyendo la parte tecnológica a las TICs.']);

        DB::table('areas')->insert(['nombre' => 'Procesamiento de lenguaje natural', 'descripcion' => 'El campo de Procesamiento de Lenguaje Natural (PLN) tiene como objetivo conseguir que las computadoras realicen tareas útiles que involucren al lenguaje humano, tales como permitir la comunicación humano – máquina, mejorar la comunicación humano – humano, o simplemente procesar texto o voz de forma útil. Uno de los mayores retos que debe ser afrontado en el campo de PLN proviene del hecho que el lenguaje natural, a diferencia del lenguaje de máquina, es frecuentemente ambiguo. Se dice que un texto es ambiguo si es que existen múltiples alternativas de estructuras lingüísticas que pueden ser construidas para él. Por ejemplo, en la oración “Estuve esperándote en el banco” no se sabe si la persona estuvo sentada en un banco o en una institución financiera. Debido a la frecuencia con la que se presentan estos casos de ambigüedad y las complicaciones que genera para conseguir un entendimiento pleno de lo que se está expresando, la investigación en PLN presenta varios desafíos y es promete ser útil en una gran variedad de aplicaciones como: traducción automática, sistemas de preguntas y respuestas, extracción de información, elaboración automática de resúmenes, simplificación textual, entre otros. En GRPIAA, los proyectos en PLN están principalmente abocados a dos líneas de investigación: implementación de herramientas de apoyo para la redacción de textos científicos, y análisis de complejidad y simplificación de textos en español. Para ambas líneas, los proyectos involucran el uso de métodos de aprendizaje de máquina basados en corpus.']);

        DB::table('areas')->insert(['nombre' => 'Agentes y Sistemas Multiagente: web, recuperación de información, Sistemas de recomendación escalables, comercio electrónico', 'descripcion' => 'No disponible']);

        DB::table('areas')->insert(['nombre' => 'Optimización combinatoria', 'descripcion' => 'La optimización combinatoria es la búsqueda de los valores de ciertos elementos (variables) que optimicen una función objetivo definida sujeta a un conjunto de restricciones. Dado que son varios los elementos que se buscan, la combinación de diferentes valores en cada variable forman conjunto de soluciones posibles. Cuando el espacio de búsqueda es "infinito" se aplican diferentes técnicas y algoritmos que ayuden a encontrar una buena solución en vez de la mejor (la que optimiza la función) ya que el costo (tiempo) de realizar la búsqueda de la mejor puede ser demasiado. Entonces se evalúa el costo-beneficio del problema para aceptar una buena solución encontrada.']);

        DB::table('areas')->insert(['nombre' => 'Aplicaciones de grafos', 'descripcion' => 'No disponible']);

        DB::table('areas')->insert(['nombre' => 'Bioinformática', 'descripcion' => 'No disponible']);
    }
}
